name: pyldn

dependencies:
  - python>=3.4
  - numpy>=1.9.2
  - pandas=0.16.1
  - blaze=0.8.0
  - odo=0.3.2
  - bokeh=0.9.0
  - joblib=0.8.4
  - ipython=3.1.0
  - ipython-notebook=3.1.0
  - flask=0.10.1
  - matplotlib=1.4.3
  - seaborn=0.5.1
  - cytoolz=0.7.3
